#include "core/RuleExport.h"

#include "core/SceneStore.h"

#include <QFile>
#include <QFileInfo>

namespace rostrum::rule_export {

namespace {

QString jsonString(const QString &s)
{
    QString out;
    out.reserve(s.size() + 2);
    out += QLatin1Char('"');
    for (const QChar c : s) {
        if (c == QLatin1Char('"') || c == QLatin1Char('\\')) {
            out += QLatin1Char('\\');
            out += c;
        } else if (c.unicode() >= 0x20) {
            out += c;
        }
    }
    out += QLatin1Char('"');
    return out;
}

QString propertyFor(MatchKey key)
{
    return key == MatchKey::Binary ? QStringLiteral("application.process.binary") : QStringLiteral("application.name");
}

QString fragment(const char *array, const QString &readBy, const Scene &scene)
{
    const auto rules = exportableRules(scene);
    if (rules.isEmpty()) {
        return {};
    }
    QString out;
    out += QStringLiteral("# Generated by Rostrum from the default scene \"%1\". Edits are overwritten.\n").arg(scene.name);
    out += QStringLiteral("# %1\n").arg(readBy);
    out += QStringLiteral("# While Rostrum runs it routes apps itself. If a bus is missing, WirePlumber uses the\n");
    out += QStringLiteral("# default sink.\n");
    out += QLatin1String(array) + QStringLiteral(" = [\n");
    for (const auto &r : rules) {
        out += QStringLiteral("    {\n");
        out += QStringLiteral("        matches = [ { %1 = %2 } ]\n")
                   .arg(propertyFor(r.key), jsonString(QLatin1Char('~') + caseInsensitiveRegex(r.match)));
        out += QStringLiteral("        actions = { update-props = { %1 = %2 } }\n")
                   .arg(QLatin1String(kTargetProperty), jsonString(QStringLiteral("rostrum.") + r.busId));
        out += QStringLiteral("    }\n");
    }
    out += QStringLiteral("]\n");
    return out;
}

bool writeOrRemove(const QString &path, const QString &text, QString *error)
{
    if (text.isEmpty()) {
        if (QFile::exists(path) && !QFile::remove(path)) {
            if (error) {
                *error = QStringLiteral("Could not remove %1.").arg(path);
            }
            return false;
        }
        return true;
    }
    if (QFileInfo::exists(path) && SceneStore::readFile(path, nullptr) == text) {
        return true;
    }
    return SceneStore::writeFile(path, text, error);
}

} // namespace

QString caseInsensitiveRegex(const QString &value)
{
    static const QString special = QStringLiteral(".[]{}()\\*+?^$|");
    QString out = QStringLiteral("^");
    for (const QChar c : value) {
        const ushort u = c.unicode();
        const bool asciiLetter = (u >= 'a' && u <= 'z') || (u >= 'A' && u <= 'Z');
        if (asciiLetter) {
            out += QLatin1Char('[') + c.toUpper() + c.toLower() + QLatin1Char(']');
        } else if (special.contains(c)) {
            out += QLatin1Char('\\') + c;
        } else {
            out += c;
        }
    }
    out += QLatin1Char('$');
    return out;
}

QList<AppRule> exportableRules(const Scene &scene)
{
    QList<AppRule> binary;
    QList<AppRule> named;
    for (const auto &r : scene.rules) {
        const Bus *bus = scene.bus(r.busId);
        if (r.match.trimmed().isEmpty() || !bus || bus->kind != BusKind::Playback) {
            continue;
        }
        (r.key == MatchKey::Binary ? binary : named).append(r);
    }
    return binary + named;
}

QString pulseFragment(const Scene &scene)
{
    return fragment(kPulseRulesArray, QStringLiteral("pipewire-pulse reads this for PulseAudio apps when it starts, normally at login."), scene);
}

QString clientFragment(const Scene &scene)
{
    return fragment(kClientRulesArray, QStringLiteral("Each native PipeWire app reads this when it starts."), scene);
}

bool apply(const Scene &scene, const QString &pulsePath, const QString &clientPath, QString *error)
{
    return writeOrRemove(pulsePath, pulseFragment(scene), error)
           && writeOrRemove(clientPath, clientFragment(scene), error);
}

} // namespace rostrum::rule_export
